[package]
name = "builtins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

fs = {path = "../fs"}
base = {path = "../base"}

# A no_std Hashmap
hashbrown = "0.14.2"

spin = "0.9.8"