mod buffer;
mod formatter;
pub mod macros;
pub mod primitives;
mod vga;
mod vga_graphics;
pub use vga_graphics::*;
pub use buffer::*;
pub use formatter::*;
pub use vga::*;
mod mode_switch;
pub use mode_switch::{switch_graphics_mode, VgaModeSwitch};